### ISSUE TITLE
Status of child pages in Dashboard view is always 'not visible'

### ISSUE THREAD

**Issue by ghost** [tangentlabs/django-fancypages#25]
MP_Node get_children just returns a query_set, so is_visible for child pages in the Dashboard view doesn't work. 

btw, really dig this project, nice and simple cms.

**Comment by roadsideseb** [comment]
Thanks for raising this and thanks for the kind words. I'm currently a bit short on time but will try to take a closer look over the next few days.

**Comment by ghost** [comment]
I guess this is all heavy work in progress... there is another bug in the same view: moving the pages throw's an error. Apparantly the Model Serializer PageMoveSerializer is configured for 3 fields which don't exist in the model. Seems from a code refactor to mp_node and be related to this bug. There are even tests for this, so i'm wondering if you perhaps simply just missed to push a few commits.
