### ISSUE TITLE
Django Compressor blocks in extrascripts and extrahead

### ISSUE THREAD

**Issue by a-musing-moose** [tangentlabs/django-fancypages#3]
Since django compressor is in setup.py does it make sense to add compress blocks to extrascripts and extrahead?

**Comment by roadsideseb** [comment]
Even though both blocks are not wrapped in compression blocks, they are still compressed. The compress is picked up from the parent container that included this. _django-compressor_ doesn't work with inheritance but it does work with `{% include %}` tags. Hence, the `compress` blocks are not required here. Does that make sense?
